// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZDW2ycKOy6OwHoF6bM-_NJKL7p_OkfdI',
    appId: '1:249484201064:web:da945c3110222fcf9ebfdd',
    messagingSenderId: '249484201064',
    projectId: 'attendanceapp-8588d',
    authDomain: 'attendanceapp-8588d.firebaseapp.com',
    storageBucket: 'attendanceapp-8588d.firebasestorage.app',
    measurementId: 'G-T4WV8BQ093',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEWXlSResg6Ikc7hPoFzO1MuyZzqm0UrY',
    appId: '1:249484201064:android:b7639af18a902d2c9ebfdd',
    messagingSenderId: '249484201064',
    projectId: 'attendanceapp-8588d',
    storageBucket: 'attendanceapp-8588d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQkDE2hvuM-Et-PFFQRldxVaSlQzaIks0',
    appId: '1:249484201064:ios:fa2573b80a66e1c29ebfdd',
    messagingSenderId: '249484201064',
    projectId: 'attendanceapp-8588d',
    storageBucket: 'attendanceapp-8588d.firebasestorage.app',
    iosBundleId: 'com.example.attendanceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQkDE2hvuM-Et-PFFQRldxVaSlQzaIks0',
    appId: '1:249484201064:ios:fa2573b80a66e1c29ebfdd',
    messagingSenderId: '249484201064',
    projectId: 'attendanceapp-8588d',
    storageBucket: 'attendanceapp-8588d.firebasestorage.app',
    iosBundleId: 'com.example.attendanceapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZDW2ycKOy6OwHoF6bM-_NJKL7p_OkfdI',
    appId: '1:249484201064:web:1ac73d1ac6209da19ebfdd',
    messagingSenderId: '249484201064',
    projectId: 'attendanceapp-8588d',
    authDomain: 'attendanceapp-8588d.firebaseapp.com',
    storageBucket: 'attendanceapp-8588d.firebasestorage.app',
    measurementId: 'G-V08FPZXY3M',
  );
}
