import 'package:flutter/material.dart';
import 'package:attendanceapp/pages/login_user_page.dart';
import 'package:attendanceapp/pages/register_user_page.dart';
import 'package:attendanceapp/services/camera_service.dart'; // ✅ import CameraService
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI
import 'widgets/firestore_demo.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await CameraService().initCamera(forceReinitOnWeb: true); // ✅ Initialize shared camera

  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Attendance App',
      debugShowCheckedModeBanner: false,
      initialRoute: '/login',
      //Debugger for Firestore, remove during production START
      builder: (context, child) {
        // Wrap all pages in a Stack
        return Stack(
          children: [
            child!,                     // The page (login/register/etc)
            Positioned(
              top: 0,
              right: 0,
              child: SizedBox(
                width: 250,
                height: 150,
                child: Card(
                  color: Colors.white70,
                  child: FirestoreDemo(), // Your debug widget
                ),
              ),
            ),
          ],
        );
      },
      //Debugger for Firestore, remove during production END
      routes: {
        '/register': (context) => const RegisterUserPage(), // ✅ no camera param
        '/login': (context) => const LoginUserPage(),       // ✅ no camera param
      },
    );
  }

}
