import 'package:flutter/material.dart';
import 'package:attendanceapp/pages/login_user_page.dart';
import 'package:attendanceapp/pages/register_user_page.dart';
import 'package:attendanceapp/services/camera_service.dart'; // ✅ import CameraService
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI
import 'widgets/firestore_demo.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await CameraService().initCamera(forceReinitOnWeb: true); // ✅ Initialize shared camera

  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Attendance App',
      debugShowCheckedModeBanner: false,
      initialRoute: '/login',
      //Debugger for Firestore, remove during production START
      // 🔹 Global debug overlay
      builder: (context, child) {
        return Stack(
          children: [
            child!, // your normal pages

            // Overlay FirestoreDemo at bottom center
            Positioned(
              bottom: 16,
              left: 0,
              right: 0,
              child: Center(
                child: ConstrainedBox(
                  constraints: const BoxConstraints(maxWidth: 320),
                  child: Card(
                    elevation: 6,
                    margin: const EdgeInsets.all(8),
                    child: const FirestoreDemo(),
                  ),
                ),
              ),
            ),
          ],
        );
      },
      //Debugger for Firestore, remove during production END
      routes: {
        '/register': (context) => const RegisterUserPage(), // ✅ no camera param
        '/login': (context) => const LoginUserPage(),       // ✅ no camera param
      },
    );
  }

}
